# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build & Deploy

on:
  push:
    branches: [main]

permissions: {}

jobs:
  build:
    name: Build repository
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Build zips
        run: make

      - name: Upload Pages artifact
        uses: LouisBrunner/.github/.github/actions/upload-pages@main
        with:
          path: out/

  deploy:
    name: Deploy to GitHub Pages
    needs: [build]
    permissions:
      pages: write
      id-token: write
    uses: LouisBrunner/.github/.github/workflows/deploy-pages.yml@main
