name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build repository
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Build zips
        run: make

      - name: Upload Pages artifact
        uses: LouisBrunner/.github/.github/actions/upload-pages@main
        with:
          path: out/

  deploy:
    name: Deploy to GitHub Pages
    needs: [build]
    uses: LouisBrunner/.github/.github/workflows/deploy-pages.yml@main
