name: Lint

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build zips
        run: make

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: out/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
